version: '3.7'

services: 
  bot:
    container_name: chat_bot
    build: ./bot
    depends_on: 
      - backend
    command: python chat_bot.py
    volumes: 
      - ./bot:/app
    env_file: 
      - ./credentials.env
    links:
      - "backend:django"
  backend:
    container_name: django-backend
    build: ./backend
    depends_on: 
      - db
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./backend:/app
    ports: 
      - 8000:8000
    env_file:
      - ./credentials.env
    depends_on:
      - db
  db: 
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
volumes:
  postgres_data:
  