version: '3.7'

services: 
  backend:
    container_name: django-backend
    build: ./backend
    depends_on: 
      - db
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./backend:/app
    ports: 
      - 8000:8000
    env_file:
      - ./backend/backend.env
    depends_on:
      - db
  redis:
    image: redis:latest
    restart: always
    ports: 
      - "6379:6379"
  db: 
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER="${PSQL_USER}"
      - POSTGRES_PASSWORD="${PSQL_PASS}"
      - POSTGRES_DB="${PSQL_DB}"
volumes:
  postgres_data:
  