# Generated by Django 3.2.3 on 2021-05-19 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bot_time',
            },
        ),
        migrations.CreateModel(
            name='StreamUsers',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_watched', models.DateTimeField(auto_now=True)),
                ('following', models.BooleanField()),
                ('followed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'followers',
            },
        ),
        migrations.CreateModel(
            name='TextCommands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=60)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'text_commands',
            },
        ),
        migrations.CreateModel(
            name='FalseCommands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('command', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='false_commands', to='chat_data.streamusers')),
            ],
            options={
                'db_table': 'false_commands',
            },
        ),
        migrations.CreateModel(
            name='CommandUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('command', models.CharField(max_length=60)),
                ('is_custom', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='command_usage', to='chat_data.streamusers')),
            ],
            options={
                'db_table': 'command_use',
            },
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='chat_data.streamusers')),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
    ]
