# Generated by Django 3.2.3 on 2021-05-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_data', '0003_featurerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='room',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
