# Generated by Django 3.2.3 on 2021-06-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_data', '0006_chatmessages_twith_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsToMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_monitored', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'rooms_to_monitor',
            },
        ),
    ]
