# Generated by Django 3.2.3 on 2021-07-10 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_data', '0007_roomstomonitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='commanduse',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cu_message', to='chat_data.chatmessages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='falsecommands',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fc_message', to='chat_data.chatmessages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='msg_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fr_message', to='chat_data.chatmessages'),
            preserve_default=False,
        ),
    ]
