# Generated by Django 3.2.3 on 2021-07-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_data', '0008_auto_20210710_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessages',
            options={'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name_plural': 'Chat Rooms'},
        ),
        migrations.AlterModelOptions(
            name='falsecommands',
            options={'verbose_name_plural': 'False Commands'},
        ),
        migrations.AlterModelOptions(
            name='roomstomonitor',
            options={'verbose_name_plural': 'Rooms to Monitor'},
        ),
        migrations.AlterModelOptions(
            name='streamusers',
            options={'verbose_name_plural': 'Stream Users'},
        ),
        migrations.AlterModelOptions(
            name='textcommands',
            options={'verbose_name_plural': 'Text Commands'},
        ),
        migrations.RemoveField(
            model_name='chatmessages',
            name='id',
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='twith_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
